n=input("enter the name")
cl=input("enter the class")
s=input("enter the section")
p=int(input("enter the Physics marks"))
c=int(input("enter the chemistry marks"))
m=int(input("enter the maths marks"))
e=int(input ("enter the english manrks"))
cs=int(input("enter the computer science marks"))
M=(p+c+m+e+cs)
per=(M)/5
print("\n\n\n")
print("                 MARKSHEET")
print("                 *********")
print("Name:",n,"          Class:",cl,    "Section:",s  )
print("______________________________________________________")
print("Subject          M.M                 Marks Obtain")
print("______________________________________________________")
print("physics         100                      ",p)
print("Chemistry       100                      ",c)
print("Maths           100                      ",m)
print("English         100                      ",e)
print("Computer Sc.    100                     ",cs)
print("______________________________________________________")
print("Total Marks     500                      ",M)
print("______________________________________________________")
print("PERCENTAGE                            =",per)
if(per>=33):
  print("Qualified                               pass")
else:
  print(" Qualified                              fail")
